package shim

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const credentialPlaceholder = "placeholder"

// Options configures generated command shims.
type Options struct {
	ProxyURL   string // e.g. http://127.0.0.1:11111
	BundlePath string // absolute path to combined CA bundle PEM
	BinDir     string // output directory for shim scripts
}

type spec struct {
	name string
	env  func(Options) [][2]string
}

var specs = []spec{
	{
		name: "gh",
		env: func(opts Options) [][2]string {
			return [][2]string{
				{"HTTP_PROXY", opts.ProxyURL},
				{"HTTPS_PROXY", opts.ProxyURL},
				{"http_proxy", opts.ProxyURL},
				{"https_proxy", opts.ProxyURL},
				{"GH_TOKEN", credentialPlaceholder},
			}
		},
	},
	{
		name: "gem",
		env: func(opts Options) [][2]string {
			return [][2]string{
				{"GEM_HOST_API_KEY", credentialPlaceholder},
				{"SSL_CERT_FILE", opts.BundlePath},
				{"http_proxy", opts.ProxyURL},
				{"https_proxy", opts.ProxyURL},
			}
		},
	},
	{
		name: "bundle",
		env: func(opts Options) [][2]string {
			return [][2]string{
				{"HTTP_PROXY", opts.ProxyURL},
				{"HTTPS_PROXY", opts.ProxyURL},
				{"http_proxy", opts.ProxyURL},
				{"https_proxy", opts.ProxyURL},
				{"BUNDLE_SSL_CA_CERT", opts.BundlePath},
				{"SSL_CERT_FILE", opts.BundlePath},
			}
		},
	},
}

// Generate writes executable shim scripts into opts.BinDir.
func Generate(opts Options) ([]string, error) {
	if opts.ProxyURL == "" {
		return nil, fmt.Errorf("proxy URL is required")
	}
	if opts.BundlePath == "" {
		return nil, fmt.Errorf("bundle path is required")
	}
	if opts.BinDir == "" {
		return nil, fmt.Errorf("bin dir is required")
	}

	if err := os.MkdirAll(opts.BinDir, 0o700); err != nil {
		return nil, fmt.Errorf("create bin dir: %w", err)
	}

	var written []string
	for _, spec := range specs {
		path, err := writeShim(opts, spec)
		if err != nil {
			return written, err
		}
		written = append(written, path)
	}

	return written, nil
}

func writeShim(opts Options, spec spec) (string, error) {
	realPath, err := resolveExecutable(spec.name, opts.BinDir)
	if err != nil {
		return "", err
	}

	shimPath := filepath.Join(opts.BinDir, spec.name)
	content := renderScript(realPath, spec.env(opts))

	if err := os.WriteFile(shimPath, []byte(content), 0o755); err != nil {
		return "", fmt.Errorf("write shim %q: %w", shimPath, err)
	}

	return shimPath, nil
}

func resolveExecutable(name, shimDir string) (string, error) {
	path, err := exec.LookPath(name)
	if err != nil {
		return "", fmt.Errorf("resolve %q: %w (is it installed and on PATH?)", name, err)
	}

	absPath, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve %q: %w", name, err)
	}

	shimDirAbs, err := filepath.Abs(shimDir)
	if err != nil {
		return "", err
	}

	if strings.HasPrefix(absPath, shimDirAbs+string(filepath.Separator)) {
		return "", fmt.Errorf("resolve %q: found existing shim at %q; temporarily remove %q from PATH and re-run", name, absPath, shimDirAbs)
	}

	return absPath, nil
}

func renderScript(realPath string, env [][2]string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by coronagraph. Do not edit.\n")
	for _, pair := range env {
		b.WriteString("export ")
		b.WriteString(pair[0])
		b.WriteString("=")
		b.WriteString(shellQuote(pair[1]))
		b.WriteString("\n")
	}
	b.WriteString("exec ")
	b.WriteString(shellQuote(realPath))
	b.WriteString(` "$@"`)
	b.WriteString("\n")
	return b.String()
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	if !strings.ContainsAny(value, " \t\n'\"\\$`") {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", `'"\''"`) + "'"
}
